from fastapi import APIRouter, HTTPException, Request

from app.api.routers.solve.payload_schemas import ComparisonRequest
from app.api.routers.solve.response_schemas import (
    ComparisonResponse,
)
from app.core.operations.solve import run_comparision
from app.exceptions import (
    InstanceParseException,
    ModelLoadException,
    ModelNotFoundException,
)

router = APIRouter(
    prefix="/solve",
    tags=["Solve"],
)


@router.post(
    "/comparison",
    description=(
        "Run both algorithms in parallel — the GA with a random initial population "
        "and the GA with an initial population generated by the DRL model — and compare their results."
    ),
    response_model=ComparisonResponse,
)
def handle_run_comparison(params: ComparisonRequest, request: Request):
    try:
        session_id = request.state.session_id
        return run_comparision(params, session_id=session_id)
    except InstanceParseException as e:
        raise HTTPException(
            status_code=404,
            detail=f"Instance '{e.filename}' not found: {e.reason}",
        )
    except ModelNotFoundException as e:
        raise HTTPException(
            status_code=404,
            detail=f"Model '{e.model_id}' not found. Please train it first.",
        )
    except ModelLoadException as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to load model '{e.model_id}': {e.reason}",
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Unexpected error during comparison: {str(e)}",
        )
