from fastapi import APIRouter, HTTPException

from app.api.routers.solve.payload_schemas import ComparisonRequest
from app.api.routers.solve.response_schemas import (
    ComparisonResponse,
)
from app.core.operations.solve import run_comparision
from app.exceptions import ModelLoadException, ModelNotFoundException

router = APIRouter(
    prefix="/solve",
    tags=["Solve"],
)


@router.post(
    "/comparison",
    description=(
        "Run both algorithms in parallel — the GA with a random initial population "
        "and the GA with an initial population generated by the DRL model — and compare their results."
    ),
    response_model=ComparisonResponse,
)
def handle_run_comparison(request: ComparisonRequest):
    try:
        return run_comparision(request)
    except ModelNotFoundException as e:
        raise HTTPException(
            status_code=404,
            detail=f"Model '{e.model_id}' not found. Please train it first.",
        )
    except ModelLoadException as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to load model '{e.model_id}': {e.reason}",
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Unexpected error during comparison: {str(e)}",
        )
